### ISSUE TITLE
Tlsexception

### ISSUE THREAD

**Issue by Anasaurus** [afauch/Wit1#2]
When I click on space bar, I receive this error: TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates)

**Comment by afauch** [comment]
@Anasaurus are you running on Windows or Mac?

**Comment by Anasaurus** [comment]
Windows 10

**Comment by afauch** [comment]
This is probably a start:
http://www.mono-project.com/docs/faq/security/

On Thu, Mar 17, 2016 at 4:28 PM, Anasaurus notifications@github.com wrote:

> Windows 10
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/afauch/Wit1/issues/2#issuecomment-198088836

## 

  Aaron Faucher
  afaucher.me
  aaron.faucher@gmail.com
  978.424.1590

**Comment by afauch** [comment]
http://stackoverflow.com/questions/4926676/mono-webrequest-fails-with-https

On Thu, Mar 17, 2016 at 4:43 PM, Aaron Faucher aaron.faucher@gmail.com
wrote:

> This is probably a start:
> http://www.mono-project.com/docs/faq/security/
> 
> On Thu, Mar 17, 2016 at 4:28 PM, Anasaurus notifications@github.com
> wrote:
> 
> > Windows 10
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/afauch/Wit1/issues/2#issuecomment-198088836
> 
> ## 
> 
>   Aaron Faucher
>   afaucher.me
>   aaron.faucher@gmail.com
>   978.424.1590

## 

  Aaron Faucher
  afaucher.me
  aaron.faucher@gmail.com
  978.424.1590

**Comment by afauch** [comment]
@Anasaurus here's a temporary fix:
- Open "AudioToHttp.cs"
- Find the line that reads `void Start()`
- Paste this directly below that line:
  `System.Net.ServicePointManager.ServerCertificateValidationCallback
       = (a, b, c, d) => { return true; };`

Please note that this solution leaves a security vulnerability because it turns off SSL for the request. More info here: http://answers.unity3d.com/comments/803379/view.html

But at very least that should get you up and running.

The more sustainable solution requires you to import the CA certificate into your Mono Trust Store, which is outlined here: http://www.mono-project.com/docs/faq/security/

Unfortunately as a non-Windows user I found this confusing and haven't yet figured it out.

**Comment by Anasaurus** [comment]
I try it several times but this method didn't works,  so there is another alternative solution?

**Comment by afauch** [comment]
@Anasaurus When you try this, are you still receiving the same error as
before? Or is it returning a different error?

**Comment by Anasaurus** [comment]
yes: 
Listening for command
UnityEngine.MonoBehaviour:print(Object)

## AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:49)

Thinking ...
UnityEngine.MonoBehaviour:print(Object)

## AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:57)

C:/Users/Documents/Speech Recognition007/Assets\sample.wav
UnityEngine.Debug:Log(Object)
SavWav:Save(String, AudioClip) (at Assets/UserScripts/SavWav.cs:43)

## AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:61)

WebException: The request timed out
System.Net.HttpWebRequest.GetRequestStream ()
AudioToHttp.GetJSONText (System.String file) (at Assets/UserScripts/AudioToHttp.cs:95)

## AudioToHttp.Update () (at Assets/UserScripts/AudioToHttp.cs:71)

Http went through ok
UnityEngine.MonoBehaviour:print(Object)
AudioToHttp:GetJSONText(String) (at Assets/UserScripts/AudioToHttp.cs:113)
AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:71)

---

{
  "msg_id" : "e3cec583-d992-4763-a31c-09ef9c77117f",
  "_text" : "the",
  "outcomes" : [ {
    "_text" : "the",
    "confidence" : 0.482,
    "intent" : "move_object",
    "entities" : { }
  } ]
}
UnityEngine.MonoBehaviour:print(Object)
AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:72)

---

{
  "msg_id" : "e3cec583-d992-4763-a31c-09ef9c77117f",
  "_text" : "the",
  "outcomes" : [ {
    "_text" : "the",
    "confidence" : 0.482,
    "intent" : "move_object",
    "entities" : { }
  } ]

## }

UnityEngine.MonoBehaviour:print(Object)
AudioToHttp:DoParse(String) (at Assets/UserScripts/AudioToHttp.cs:132)
AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:73)

---

SimpleJSON: {"msg_id":"e3cec583-d992-4763-a31c-09ef9c77117f", "_text":"the", "outcomes":[ {"_text":"the", "confidence":"0.482", "intent":"move_object", "entities":{}} ]}
UnityEngine.MonoBehaviour:print(Object)
AudioToHttp:DoParse(String) (at Assets/UserScripts/AudioToHttp.cs:134)

## AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:73)

Subject: 
UnityEngine.MonoBehaviour:print(Object)
AudioToHttp:DoParse(String) (at Assets/UserScripts/AudioToHttp.cs:137)

## AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:73)

Destination: 
UnityEngine.MonoBehaviour:print(Object)
AudioToHttp:DoParse(String) (at Assets/UserScripts/AudioToHttp.cs:140)
AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:73)

---

Didn't understand you, try again.
UnityEngine.MonoBehaviour:print(Object)
AudioToHttp:FindObjects(String, String) (at Assets/UserScripts/AudioToHttp.cs:154)
AudioToHttp:DoParse(String) (at Assets/UserScripts/AudioToHttp.cs:146)
AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:73)

**Comment by afauch** [comment]
@Anasaurus well, we're making progress - these logs show that the HttpWebRequest is going through, and that wit.ai is returning a response. Here are two possible reasons it's not working.

## Command Issue

Run the scene. Hold the spacebar and say "Put the ball on the chair" slowly and loudly. **Don't release the spacebar until you are done voicing your command.** You should see a log come back that looks something like this:

```
{
  "msg_id" : "3b0561d4-3398-4dbf-91c2-561cb7d8d06e",
  "_text" : "put the ball on the chair",
  "outcomes" : [ {
    "_text" : "put the ball on the chair",
    "confidence" : 0.88,
    "intent" : "move_object",
    "entities" : {
      "subject" : [ {
        "type" : "value",
        "value" : "ball"
      } ],
      "destination" : [ {
        "type" : "value",
        "value" : "chair"
      } ]
    }
  } ]
}
UnityEngine.MonoBehaviour:print(Object)
AudioToHttp:DoParse(String) (at Assets/UserScripts/AudioToHttp.cs:131)
AudioToHttp:Update() (at Assets/UserScripts/AudioToHttp.cs:72)
```

If you don't see that, then our issue is probably in how the audio is being sent to wit.ai.

## SavWav issue

It looks like there's may been an issue with how the `SavWav.cs` plugin is saving the recording of your voice before sending it to Wit.ai. I noticed this in the logs: `C:/Users/Documents/Speech Recognition007/Assets\sample.wav`. The filepath seems odd: backslashes for most of the directory path, but then a slash in front of `\sample.wav`.

Here's how we can check if this is a problem:
Follow the same steps as above: run the scene, hold the spacebar, voice a new command ("Move the chair to the table"), then release the spacebar. In your Unity project folder, you should see a file called `sample.wav`. Select this file and click the play button in Unity. 
![image](https://cloud.githubusercontent.com/assets/10394825/14061226/f910ea6a-f348-11e5-9bac-a89d2c03e9fa.png)
You should hear the last command that you voiced to the computer. If you're hearing something different, then we know that there's something wrong with how the file is being saved.

Try out both of these and let me know how it turns out!

**Comment by Anasaurus** [comment]
Yes Finally it works, thank you for your help, please have you any idea how can appear a part instead to move it? for example when you say I want the part X, it comes...
to do so, I think we should build a big database of parts, isn't?

**Comment by afauch** [comment]
@Anasaurus Good idea. I'll try to write this functionality into the next commit! You can 'watch' the wit3d repository on Github to get a notification when I upload this.

**Comment by Anasaurus** [comment]
yes this technique is very useful on mechanical engineering application, for instance, when you work on virtual assembly design ( using oculus lift and leap motion), you need just calling the name of part, tools or component and they appear near your hands.
the integration between UINITY and Leap motion is done. So, now I should model on CATIA or Solidworks the component of some mechanisms or machines. then we will integrate on unity a database of all parts.
I'm very glad to work with you, if you have some question on mechanical design domain, I remain at your disposal.
Cheers

**Comment by nasashi** [comment]
hi @afauch when i give the voice command i got this error

NullReferenceException: Object reference not set to an instance of an object
Wit3D.MoveObject (System.String textToParse) (at Assets/UserScripts/_MoveObject.cs:32)
Wit3D.Handle (System.String textToParse) (at Assets/UserScripts/_Handle.cs:20)
Wit3D.Update () (at Assets/UserScripts/Wit3D.cs:101)

how to solve that?

**Comment by anuproy** [comment]
Hi @afauch I can see two compile error how can I solve it any idea?

1. Assets\UserScripts\Wit3D.cs(50,2): error CS0246: The type or namespace name 'UnityWebRequest' could not be found (are you missing a using directive or an assembly reference?)
2. Assets\Reference.cs(25,2): error CS0246: The type or namespace name 'UnityWebRequest' could not be found (are you missing a using directive or an assembly reference?)
